version: '3'

services:
  node:
    build:
      context: ./node
    container_name: node
    image: matheusmartinez/node:prod
    volumes:
      - ./node:/app
    networks:
      - node-network
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nodedb
      MYSQL_PASSWORD: nodedb
    networks:
      - node-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: matheusmartinez/nginx-node:prod
    ports:
      - '8080:80'
    depends_on:
      - node
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
